SELECT AVG(CAST(DATEDIFF(day, o.Date_Time, i.DELIVERY_DATE) AS float)) AS avg_delivery_time
FROM ORDERS o
	JOIN ITEMS_IN_ORDERS i ON o.ORDER_ID = i.ORDER_ID
	JOIN SIB_1 s ON i.STOCK_ID = s.Stock_ID AND i.BOOKSTORE_ID = s.BOOKSTORE_ID
	JOIN PUBLICATION p ON s.Pub_ID = p.Pub_ID
WHERE YEAR(o.Date_Time) = 2022 AND MONTH(o.Date_Time) = 6 AND i.DELIVERY_DATE IS NOT NULL