SELECT Pub_ID, AVG(CAST(RATING AS FLOAT)) as avg_rating
FROM FEEDBACK
	INNER JOIN ITEMS_IN_ORDERS
		ON FEEDBACK.STOCK_ID = ITEMS_IN_ORDERS.STOCK_ID
		AND FEEDBACK.ITEM_ID = ITEMS_IN_ORDERS.ITEM_ID
		AND FEEDBACK.ORDER_ID = ITEMS_IN_ORDERS.ORDER_ID
	INNER JOIN SIB_1 
		ON FEEDBACK.STOCK_ID = SIB_1.Stock_ID
		AND ITEMS_IN_ORDERS.BOOKSTORE_ID = SIB_1.BOOKSTORE_ID
	INNER JOIN ORDERS
		ON FEEDBACK.ORDER_ID = ORDERS.ORDER_ID
WHERE PUB_ID IN (
/* Find items that have at least 10 ratings of '5's in Aug 2022. */
	SELECT Pub_ID
	FROM FEEDBACK
		INNER JOIN ITEMS_IN_ORDERS
			ON FEEDBACK.ITEM_ID = ITEMS_IN_ORDERS.ITEM_ID
			AND FEEDBACK.STOCK_ID = ITEMS_IN_ORDERS.STOCK_ID
			AND FEEDBACK.ORDER_ID = ITEMS_IN_ORDERS.ORDER_ID
		INNER JOIN SIB_1 
			ON FEEDBACK.STOCK_ID = SIB_1.Stock_ID
			AND ITEMS_IN_ORDERS.BOOKSTORE_ID = SIB_1.BOOKSTORE_ID
		INNER JOIN ORDERS
			ON FEEDBACK.ORDER_ID = ORDERS.ORDER_ID
	WHERE MONTH(ORDERS.Date_Time) = 8
		AND YEAR(ORDERS.Date_Time) = 2022
		AND RATING = 5 
	GROUP BY Pub_ID 
	HAVING COUNT(*) >= 10)
GROUP BY Pub_ID 
ORDER BY avg_rating